const TOGGLE_MODAL = 'TOGGLE_MODAL';
const ADD_EDIT_TASK = 'ADD_EDIT_TASK';
const EDIT_TASK = 'EDIT_TASK';
const DELETE_TASK = 'DELETE_TASK';
const DELETE_ALL_TASK = 'DELETE_ALL_TASK';
const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
const SEARCH_TASKS = 'SEARCH_TASKS';

export {
  TOGGLE_MODAL,
  ADD_EDIT_TASK,
  EDIT_TASK,
  DELETE_TASK,
  DELETE_ALL_TASK,
  TOGGLE_FAVORITE,
  SEARCH_TASKS,
};
